/**
 * \file
 *
 * \brief Driver ISR.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include <driver_init.h>
#include <compiler.h>
#include "logic_functions.h"

ISR (PCINT2_vect)
{
	uint8_t changedbits;
	changedbits = PIND ^ historico_da_porta.D;
	historico_da_porta.D = PIND;

	if(changedbits & (1 << PIND2))
	{
		/* PCINT18 changed */
		temp_interrupcao.d2 += 1;
		if ((temp_interrupcao.d2 == 2)&&( (TELA.pagina_atual==2)||(TELA.pagina_atual==3)
		||(TELA.pagina_atual==5)) )
		{
			temp_interrupcao.d2 = 0;
			if (edicao.esta_editando == 0)
			{
				edicao.esta_editando = 1;
				edicao.esta_editando_radiacao_solar = 1;
				edicao.tela_antiga = TELA.pagina_atual;
				editar_valor();
				}else{
				if (edicao.esta_editando_radiacao_solar == 1)
				{
					salvar_valor();
				}
			}
		}
	}
	
	if(changedbits & (1 << PIND3))
	{
		/* PCINT19 changed */
		temp_interrupcao.d3 += 1;
		if ((temp_interrupcao.d3 == 2)&&( (TELA.pagina_atual==2)||(TELA.pagina_atual==3)
		||(TELA.pagina_atual==5)) )
		{
			temp_interrupcao.d3 = 0;
			if (edicao.esta_editando == 0)
			{
				edicao.esta_editando = 1;
				edicao.esta_editando_temperatura = 1;
				edicao.tela_antiga = TELA.pagina_atual;
				editar_valor();
				}else{
				if (edicao.esta_editando_temperatura == 1)
				{
					salvar_valor();
				}
			}
		}
	}

	if(changedbits & (1 << PIND4))
	{
		/* PCINT20 changed */
		temp_interrupcao.d4 += 1;
		if ((temp_interrupcao.d4 == 2)&&( (TELA.pagina_atual==2)||(TELA.pagina_atual==3)
		||(TELA.pagina_atual==5)))
		{
			temp_interrupcao.d4 = 0;
			if (edicao.esta_editando == 0)
			{
				edicao.esta_editando = 1;
				edicao.esta_editando_umidade = 1;
				edicao.tela_antiga = TELA.pagina_atual;
				editar_valor();
				}else{
				if (edicao.esta_editando_umidade == 1)
				{
					salvar_valor();
				}
			}
		}
	}
}

ISR (PCINT0_vect)
{
	uint8_t changedbits;
	changedbits = PINB ^ historico_da_porta.B;
	historico_da_porta.B = PINB;
	
	if(changedbits & (1 << PINB6))
	{
		/* PCINT6 changed */
		temp_interrupcao.b6 += 1;
		if (temp_interrupcao.b6 == 2)
		{
			temp_interrupcao.b6 = 0;
			if(edicao.esta_editando == 1){
				TELA.pagina_atual = edicao.tela_antiga;
				reset_edicao();
				atualizar_tela();
				}else{
				mudar_tela();
			}
		}
	}
}
